// src/lib/mockData.ts
// Dados de demonstração para validação com Divino TV

export const MOCK_DATA = {

  campeonatos: [
    { id: 1, nome: 'Copa Divino TV 2026',    categoria: 'Amador',       temporada: 2026, status: 'ativo', org_id: '1', modalidade: 'campo' as const,  formato: 'copa'        as const },
    { id: 2, nome: 'Liga Sub-20 ABC 2026',   categoria: 'Sub-20',       temporada: 2026, status: 'ativo', org_id: '1', modalidade: 'campo' as const,  formato: 'liga'        as const },
    { id: 3, nome: 'Kings League Divino TV', categoria: 'Kings League', temporada: 2026, status: 'ativo', org_id: '1', modalidade: 'campo' as const,  formato: 'kings_league' as const },
    { id: 4, nome: 'Copa Divino Salão',      categoria: 'Futsal',       temporada: 2026, status: 'ativo', org_id: '1', modalidade: 'salão' as const,  formato: 'futsal'      as const },
  ],

  times: [
    // ── Campo – Copa DTV / Sub-20 ─────────────────────────
    { id: 1,  nome: 'Flamengo Várzea',     cidade: 'Santo André' },
    { id: 2,  nome: 'Corinthians Base',    cidade: 'São Paulo'   },
    { id: 3,  nome: 'Santos FC Amador',    cidade: 'Santos'      },
    { id: 4,  nome: 'Palmeiras Jovem',     cidade: 'São Paulo'   },
    { id: 5,  nome: 'EC Mauá FC',          cidade: 'Mauá'        },
    { id: 6,  nome: 'União Diadema',       cidade: 'Diadema'     },
    // ── Kings League – Grupo A ────────────────────────────
    { id: 7,  nome: 'Los Galácticos',      cidade: 'São Paulo'   },
    { id: 8,  nome: 'Team Craque',         cidade: 'Santo André' },
    { id: 9,  nome: 'Divino All Stars',    cidade: 'São Paulo'   },
    { id: 10, nome: 'Rei da Bola FC',      cidade: 'São Caetano' },
    // ── Kings League – Grupo B ────────────────────────────
    { id: 11, nome: 'Seleção ABC',         cidade: 'Santo André' },
    { id: 12, nome: 'Dream Team DTV',      cidade: 'São Paulo'   },
    { id: 13, nome: 'Os Incríveis',        cidade: 'Mauá'        },
    { id: 14, nome: 'Time do Povo',        cidade: 'Diadema'     },
    // ── Salão ─────────────────────────────────────────────
    { id: 15, nome: 'Flash Futsal',        cidade: 'São Paulo'   },
    { id: 16, nome: 'Trovão Futsal',       cidade: 'Santo André' },
    { id: 17, nome: 'Star Futsal',         cidade: 'São Caetano' },
    { id: 18, nome: 'Relâmpago Futsal',    cidade: 'Mauá'        },
  ],

  jogadores: [
    { id: 1, nome: 'Carlos Eduardo Silva', apelido: 'Carlão',      posicao: 'atacante', time: 'Flamengo Várzea'   },
    { id: 2, nome: 'João Pedro Ramos',     apelido: 'Pedrinho',    posicao: 'meia',     time: 'Flamengo Várzea'   },
    { id: 3, nome: 'Rafael Costa Lima',    apelido: 'Rafa',        posicao: 'goleiro',  time: 'Flamengo Várzea'   },
    { id: 4, nome: 'Bruno Oliveira',       apelido: 'Brunão',      posicao: 'zagueiro', time: 'Flamengo Várzea'   },
    { id: 5, nome: 'Lucas Ferreira',       apelido: 'Luca',        posicao: 'lateral',  time: 'Flamengo Várzea'   },
    { id: 6, nome: 'André Mendes',         apelido: 'Andrezinho',  posicao: 'volante',  time: 'Corinthians Base'  },
    { id: 7, nome: 'Diego Souza',          apelido: 'Diegão',      posicao: 'atacante', time: 'Corinthians Base'  },
    { id: 8, nome: 'Mateus Alves',         apelido: 'Mateus',      posicao: 'meia',     time: 'Palmeiras Jovem'   },
  ],

  matches: [
    // ══════════════════════════════════════════════════════
    // Copa Divino TV 2026 (championship_id: 1)
    // ══════════════════════════════════════════════════════
    {
      id: 1, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 10*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera', championship_id: 1,
      mandante_id: 1, visitante_id: 2,
      mandante: { id:1, nome:'Flamengo Várzea' }, visitante: { id:2, nome:'Corinthians Base' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: { gols_mandante:0, gols_visitante:4 },
      gols: [
        { id:1, jogador:'Diegão',     minuto:12, tipo:'normal',  team:{ nome:'Corinthians Base' } },
        { id:2, jogador:'Andrezinho', minuto:38, tipo:'normal',  team:{ nome:'Corinthians Base' } },
        { id:3, jogador:'Diegão',     minuto:61, tipo:'normal',  team:{ nome:'Corinthians Base' } },
        { id:4, jogador:'Diegão',     minuto:83, tipo:'normal',  team:{ nome:'Corinthians Base' } },
      ],
      cartoes: [
        { id:1, jogador:'Brunão', minuto:45, tipo:'amarelo', team:{ nome:'Flamengo Várzea' } },
        { id:2, jogador:'Marcos', minuto:70, tipo:'amarelo', team:{ nome:'Flamengo Várzea' } },
      ],
      notas: [
        { id:1, player:{ nome:'Diegão' },     nota:9.5, melhor_jogo:true  },
        { id:2, player:{ nome:'Andrezinho' }, nota:8.0, melhor_jogo:false },
        { id:3, player:{ nome:'Rafa' },       nota:4.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'José Santos', publico:520, observacoes:'Corinthians dominante. Hat-trick de Diegão.' },
      link_video: null as string | null,
    },
    {
      id: 2, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 10*24*3600000).toISOString(),
      local: 'Arena Várzea Norte', championship_id: 1,
      mandante_id: 3, visitante_id: 4,
      mandante: { id:3, nome:'Santos FC Amador' }, visitante: { id:4, nome:'Palmeiras Jovem' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: { gols_mandante:0, gols_visitante:2 },
      gols: [
        { id:5, jogador:'Carlão', minuto:29, tipo:'normal', team:{ nome:'Palmeiras Jovem' } },
        { id:6, jogador:'Mateus', minuto:61, tipo:'normal', team:{ nome:'Palmeiras Jovem' } },
      ],
      cartoes: [
        { id:3, jogador:'Thiagão', minuto:50, tipo:'vermelho', team:{ nome:'Santos FC Amador' } },
      ],
      notas: [
        { id:4, player:{ nome:'Mateus' }, nota:8.0, melhor_jogo:true  },
        { id:5, player:{ nome:'Carlão' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Carlos Moreira', publico:210, observacoes:'Santos jogou com 10 desde os 50 minutos.' },
      link_video: null as string | null,
    },
    {
      id: 3, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 3*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera', championship_id: 1,
      mandante_id: 2, visitante_id: 3,
      mandante: { id:2, nome:'Corinthians Base' }, visitante: { id:3, nome:'Santos FC Amador' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: { gols_mandante:3, gols_visitante:0 },
      gols: [
        { id:7, jogador:'Diegão', minuto:20, tipo:'normal',  team:{ nome:'Corinthians Base' } },
        { id:8, jogador:'Júnior', minuto:44, tipo:'normal',  team:{ nome:'Corinthians Base' } },
        { id:9, jogador:'Diegão', minuto:72, tipo:'penalti', team:{ nome:'Corinthians Base' } },
      ],
      cartoes: [
        { id:4, jogador:'Thiagão', minuto:55, tipo:'amarelo', team:{ nome:'Santos FC Amador' } },
      ],
      notas: [
        { id:6, player:{ nome:'Diegão' }, nota:9.0, melhor_jogo:true  },
        { id:7, player:{ nome:'Júnior' }, nota:8.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Paulo Henrique', publico:410, observacoes:'Corinthians sólido. Diegão marca dois e Júnior sela a goleada.' },
      link_video: null as string | null,
    },
    {
      id: 4, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 3*24*3600000).toISOString(),
      local: 'Arena Várzea Norte', championship_id: 1,
      mandante_id: 4, visitante_id: 1,
      mandante: { id:4, nome:'Palmeiras Jovem' }, visitante: { id:1, nome:'Flamengo Várzea' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: { gols_mandante:2, gols_visitante:0 },
      gols: [
        { id:10, jogador:'Mateus', minuto:11, tipo:'normal', team:{ nome:'Palmeiras Jovem' } },
        { id:11, jogador:'Carlão', minuto:88, tipo:'contra', team:{ nome:'Flamengo Várzea'  } },
      ],
      cartoes: [
        { id:5, jogador:'Brunão', minuto:23, tipo:'amarelo', team:{ nome:'Flamengo Várzea' } },
      ],
      notas: [
        { id:8, player:{ nome:'Mateus' }, nota:8.5, melhor_jogo:true  },
        { id:9, player:{ nome:'Carlão' }, nota:6.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Carlos Moreira', publico:180, observacoes:'Boa atuação do Palmeiras.' },
      link_video: null as string | null,
    },
    {
      id: 5, rodada: 3, status: 'agendado',
      data_hora: new Date(Date.now() + 4*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera', championship_id: 1,
      mandante_id: 1, visitante_id: 3,
      mandante: { id:1, nome:'Flamengo Várzea' }, visitante: { id:3, nome:'Santos FC Amador' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: 'https://youtube.com/watch?v=dQw4w9WgXcQ' as string | null,
    },
    {
      id: 6, rodada: 3, status: 'agendado',
      data_hora: new Date(Date.now() + 3*3600000).toISOString(),
      local: 'Arena Várzea Norte', championship_id: 1,
      mandante_id: 2, visitante_id: 4,
      mandante: { id:2, nome:'Corinthians Base' }, visitante: { id:4, nome:'Palmeiras Jovem' },
      championship: { nome:'Copa Divino TV 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },

    // ══════════════════════════════════════════════════════
    // Liga Sub-20 ABC 2026 (championship_id: 2)
    // ══════════════════════════════════════════════════════
    {
      id: 7, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 7*24*3600000).toISOString(),
      local: 'Estádio Municipal Mauá', championship_id: 2,
      mandante_id: 5, visitante_id: 6,
      mandante: { id:5, nome:'EC Mauá FC' }, visitante: { id:6, nome:'União Diadema' },
      championship: { nome:'Liga Sub-20 ABC 2026' },
      resultado: { gols_mandante:2, gols_visitante:1 },
      gols: [
        { id:12, jogador:'Gabriel Costa', minuto:22, tipo:'normal', team:{ nome:'EC Mauá FC'      } },
        { id:13, jogador:'Felipe Neto',   minuto:55, tipo:'normal', team:{ nome:'EC Mauá FC'      } },
        { id:14, jogador:'Marcos Vini',   minuto:80, tipo:'normal', team:{ nome:'União Diadema'   } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:10, player:{ nome:'Gabriel Costa' }, nota:8.0, melhor_jogo:true  },
        { id:11, player:{ nome:'Felipe Neto' },   nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Paulo Lima', publico:140, observacoes:'Boa partida entre as equipes jovens.' },
      link_video: null as string | null,
    },
    {
      id: 8, rodada: 2, status: 'agendado',
      data_hora: new Date(Date.now() + 6*24*3600000).toISOString(),
      local: 'Arena Sub-20 ABC', championship_id: 2,
      mandante_id: 4, visitante_id: 5,
      mandante: { id:4, nome:'Palmeiras Jovem' }, visitante: { id:5, nome:'EC Mauá FC' },
      championship: { nome:'Liga Sub-20 ABC 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },

    // ══════════════════════════════════════════════════════
    // Kings League Divino TV (championship_id: 3)
    // Fase de Grupos — rodadas 1, 2, 3 (todos finalizados)
    // Semifinais — rodada 4 | Final — rodada 5 (agendados)
    // ══════════════════════════════════════════════════════

    // ── Grupo A – Rodada 1 ────────────────────────────────
    {
      id: 9, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 7, visitante_id: 8,
      mandante: { id:7, nome:'Los Galácticos' }, visitante: { id:8, nome:'Team Craque' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:2, gols_visitante:3 },
      gols: [
        { id:20, jogador:'Craque Jr.',   minuto:12, tipo:'normal', team:{ nome:'Team Craque'    } },
        { id:21, jogador:'Craque Jr.',   minuto:51, tipo:'normal', team:{ nome:'Team Craque'    } },
        { id:22, jogador:'El Galáctico', minuto:35, tipo:'normal', team:{ nome:'Los Galácticos' } },
        { id:23, jogador:'El Galáctico', minuto:72, tipo:'normal', team:{ nome:'Los Galácticos' } },
        { id:24, jogador:'Bolinha',      minuto:78, tipo:'normal', team:{ nome:'Team Craque'    } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:20, player:{ nome:'Craque Jr.'   }, nota:8.5, melhor_jogo:true  },
        { id:21, player:{ nome:'El Galáctico' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:650, observacoes:'Craque Jr. decisivo com dois gols. Kings League esquenta!' },
      link_video: null as string | null,
    },
    {
      id: 10, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 9, visitante_id: 10,
      mandante: { id:9, nome:'Divino All Stars' }, visitante: { id:10, nome:'Rei da Bola FC' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:4, gols_visitante:1 },
      gols: [
        { id:25, jogador:'Divino King',  minuto: 8, tipo:'normal', team:{ nome:'Divino All Stars' } },
        { id:26, jogador:'Messinho',     minuto:26, tipo:'normal', team:{ nome:'Divino All Stars' } },
        { id:27, jogador:'Rei',          minuto:45, tipo:'normal', team:{ nome:'Rei da Bola FC'   } },
        { id:28, jogador:'Divino King',  minuto:63, tipo:'normal', team:{ nome:'Divino All Stars' } },
        { id:29, jogador:'Bombeirinho',  minuto:85, tipo:'normal', team:{ nome:'Divino All Stars' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:22, player:{ nome:'Divino King' }, nota:9.0, melhor_jogo:true  },
        { id:23, player:{ nome:'Messinho'    }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:650, observacoes:'Divino All Stars dominante. Divino King e Messinho brilham.' },
      link_video: null as string | null,
    },

    // ── Grupo A – Rodada 2 ────────────────────────────────
    {
      id: 11, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 7, visitante_id: 9,
      mandante: { id:7, nome:'Los Galácticos' }, visitante: { id:9, nome:'Divino All Stars' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:1, gols_visitante:2 },
      gols: [
        { id:30, jogador:'Canhota',     minuto:67, tipo:'normal', team:{ nome:'Los Galácticos'  } },
        { id:31, jogador:'Divino King', minuto:24, tipo:'normal', team:{ nome:'Divino All Stars' } },
        { id:32, jogador:'Messinho',    minuto:45, tipo:'normal', team:{ nome:'Divino All Stars' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:24, player:{ nome:'Divino King' }, nota:8.0, melhor_jogo:true  },
        { id:25, player:{ nome:'Canhota'     }, nota:7.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:780, observacoes:'Divino All Stars confirma liderança do Grupo A.' },
      link_video: null as string | null,
    },
    {
      id: 12, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 8, visitante_id: 10,
      mandante: { id:8, nome:'Team Craque' }, visitante: { id:10, nome:'Rei da Bola FC' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:3, gols_visitante:0 },
      gols: [
        { id:33, jogador:'Craque Jr.', minuto:11, tipo:'normal', team:{ nome:'Team Craque' } },
        { id:34, jogador:'Craque Jr.', minuto:39, tipo:'normal', team:{ nome:'Team Craque' } },
        { id:35, jogador:'Bolinha',    minuto:82, tipo:'normal', team:{ nome:'Team Craque' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:26, player:{ nome:'Craque Jr.' }, nota:9.0, melhor_jogo:true  },
        { id:27, player:{ nome:'Bolinha'    }, nota:7.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:780, observacoes:'Team Craque goleia para assumir 2º lugar no Grupo A.' },
      link_video: null as string | null,
    },

    // ── Grupo A – Rodada 3 ────────────────────────────────
    {
      id: 13, rodada: 3, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 7, visitante_id: 10,
      mandante: { id:7, nome:'Los Galácticos' }, visitante: { id:10, nome:'Rei da Bola FC' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:3, gols_visitante:1 },
      gols: [
        { id:36, jogador:'El Galáctico', minuto:18, tipo:'normal', team:{ nome:'Los Galácticos' } },
        { id:37, jogador:'Bola Presa',   minuto:44, tipo:'normal', team:{ nome:'Los Galácticos' } },
        { id:38, jogador:'Canhota',      minuto:75, tipo:'normal', team:{ nome:'Los Galácticos' } },
        { id:39, jogador:'Rei',          minuto:81, tipo:'normal', team:{ nome:'Rei da Bola FC'  } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:28, player:{ nome:'El Galáctico' }, nota:8.0, melhor_jogo:true  },
        { id:29, player:{ nome:'Canhota'       }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:720, observacoes:'Los Galácticos garante terceiro lugar no Grupo A.' },
      link_video: null as string | null,
    },
    {
      id: 14, rodada: 3, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 8, visitante_id: 9,
      mandante: { id:8, nome:'Team Craque' }, visitante: { id:9, nome:'Divino All Stars' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'A', fase: 'grupo',
      resultado: { gols_mandante:1, gols_visitante:2 },
      gols: [
        { id:40, jogador:'Craque Jr.',  minuto:30, tipo:'normal', team:{ nome:'Team Craque'    } },
        { id:41, jogador:'Divino King', minuto:52, tipo:'normal', team:{ nome:'Divino All Stars' } },
        { id:42, jogador:'Messinho',    minuto:79, tipo:'normal', team:{ nome:'Divino All Stars' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:30, player:{ nome:'Divino King' }, nota:8.5, melhor_jogo:true  },
        { id:31, player:{ nome:'Craque Jr.'  }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Marcos Lima', publico:920, observacoes:'Divino All Stars fecha fase de grupos 100% de aproveitamento!' },
      link_video: null as string | null,
    },

    // ── Grupo B – Rodada 1 ────────────────────────────────
    {
      id: 15, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 11, visitante_id: 12,
      mandante: { id:11, nome:'Seleção ABC' }, visitante: { id:12, nome:'Dream Team DTV' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:1, gols_visitante:2 },
      gols: [
        { id:50, jogador:'Lindo',  minuto:55, tipo:'normal', team:{ nome:'Seleção ABC'    } },
        { id:51, jogador:'Magrão', minuto:22, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:52, jogador:'Magrão', minuto:71, tipo:'normal', team:{ nome:'Dream Team DTV' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:32, player:{ nome:'Magrão' }, nota:8.5, melhor_jogo:true  },
        { id:33, player:{ nome:'Lindo'  }, nota:7.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:590, observacoes:'Dream Team começa bem no Grupo B.' },
      link_video: null as string | null,
    },
    {
      id: 16, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 13, visitante_id: 14,
      mandante: { id:13, nome:'Os Incríveis' }, visitante: { id:14, nome:'Time do Povo' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:3, gols_visitante:1 },
      gols: [
        { id:53, jogador:'Fantasma', minuto: 9, tipo:'normal', team:{ nome:'Os Incríveis' } },
        { id:54, jogador:'Trovão',   minuto:34, tipo:'normal', team:{ nome:'Os Incríveis' } },
        { id:55, jogador:'Esperto',  minuto:82, tipo:'normal', team:{ nome:'Os Incríveis' } },
        { id:56, jogador:'Tonelada', minuto:60, tipo:'normal', team:{ nome:'Time do Povo' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:34, player:{ nome:'Fantasma' }, nota:8.0, melhor_jogo:true  },
        { id:35, player:{ nome:'Trovão'   }, nota:7.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:590, observacoes:'Os Incríveis com boa entrada na Kings League.' },
      link_video: null as string | null,
    },

    // ── Grupo B – Rodada 2 ────────────────────────────────
    {
      id: 17, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 11, visitante_id: 13,
      mandante: { id:11, nome:'Seleção ABC' }, visitante: { id:13, nome:'Os Incríveis' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:2, gols_visitante:1 },
      gols: [
        { id:57, jogador:'Rapidão', minuto:18, tipo:'normal', team:{ nome:'Seleção ABC'  } },
        { id:58, jogador:'Lindo',   minuto:73, tipo:'normal', team:{ nome:'Seleção ABC'  } },
        { id:59, jogador:'Fantasma',minuto:40, tipo:'normal', team:{ nome:'Os Incríveis' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:36, player:{ nome:'Rapidão'  }, nota:8.0, melhor_jogo:true  },
        { id:37, player:{ nome:'Fantasma' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:760, observacoes:'Seleção ABC reage e se mantém viva na competição.' },
      link_video: null as string | null,
    },
    {
      id: 18, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 12, visitante_id: 14,
      mandante: { id:12, nome:'Dream Team DTV' }, visitante: { id:14, nome:'Time do Povo' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:4, gols_visitante:0 },
      gols: [
        { id:60, jogador:'Magrão',   minuto: 8, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:61, jogador:'Magrão',   minuto:29, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:62, jogador:'Bombinha', minuto:45, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:63, jogador:'Veloz DTV',minuto:77, tipo:'normal', team:{ nome:'Dream Team DTV' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:38, player:{ nome:'Magrão'   }, nota:9.5, melhor_jogo:true  },
        { id:39, player:{ nome:'Bombinha' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:760, observacoes:'Dream Team arrasa e assume liderança isolada do Grupo B.' },
      link_video: null as string | null,
    },

    // ── Grupo B – Rodada 3 ────────────────────────────────
    {
      id: 19, rodada: 3, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 11, visitante_id: 14,
      mandante: { id:11, nome:'Seleção ABC' }, visitante: { id:14, nome:'Time do Povo' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:3, gols_visitante:0 },
      gols: [
        { id:64, jogador:'Lindo',   minuto:12, tipo:'normal', team:{ nome:'Seleção ABC' } },
        { id:65, jogador:'Rapidão', minuto:44, tipo:'normal', team:{ nome:'Seleção ABC' } },
        { id:66, jogador:'Lindo',   minuto:67, tipo:'normal', team:{ nome:'Seleção ABC' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:40, player:{ nome:'Lindo'   }, nota:9.0, melhor_jogo:true  },
        { id:41, player:{ nome:'Rapidão' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:830, observacoes:'Lindo brilha com dois gols e classifica a Seleção ABC.' },
      link_video: null as string | null,
    },
    {
      id: 20, rodada: 3, status: 'finalizado',
      data_hora: new Date(Date.now() - 5*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 12, visitante_id: 13,
      mandante: { id:12, nome:'Dream Team DTV' }, visitante: { id:13, nome:'Os Incríveis' },
      championship: { nome:'Kings League Divino TV' },
      grupo: 'B', fase: 'grupo',
      resultado: { gols_mandante:2, gols_visitante:2 },
      gols: [
        { id:67, jogador:'Magrão',   minuto:23, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:68, jogador:'Bombinha', minuto:61, tipo:'normal', team:{ nome:'Dream Team DTV' } },
        { id:69, jogador:'Fantasma', minuto:37, tipo:'normal', team:{ nome:'Os Incríveis'   } },
        { id:70, jogador:'Fantasma', minuto:84, tipo:'normal', team:{ nome:'Os Incríveis'   } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:42, player:{ nome:'Fantasma' }, nota:8.5, melhor_jogo:true  },
        { id:43, player:{ nome:'Magrão'   }, nota:8.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Sandra Neves', publico:1050, observacoes:'Clássico empate! Fantasma salva Os Incríveis com gol no fim.' },
      link_video: null as string | null,
    },

    // ── Semifinais (rodada 4) – Agendado ──────────────────
    {
      id: 21, rodada: 4, status: 'agendado',
      data_hora: new Date(Date.now() + 9*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 9, visitante_id: 11,
      mandante: { id:9, nome:'Divino All Stars' }, visitante: { id:11, nome:'Seleção ABC' },
      championship: { nome:'Kings League Divino TV' },
      fase: 'semi',
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
    {
      id: 22, rodada: 4, status: 'agendado',
      data_hora: new Date(Date.now() + 9*24*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 12, visitante_id: 8,
      mandante: { id:12, nome:'Dream Team DTV' }, visitante: { id:8, nome:'Team Craque' },
      championship: { nome:'Kings League Divino TV' },
      fase: 'semi',
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },

    // ── Final (rodada 5) – Agendado ───────────────────────
    {
      id: 23, rodada: 5, status: 'agendado',
      data_hora: new Date(Date.now() + 9*24*3600000 + 3*3600000).toISOString(),
      local: 'Arena Kings DTV', championship_id: 3,
      mandante_id: 9, visitante_id: 12,
      mandante: { id:9, nome:'Divino All Stars' }, visitante: { id:12, nome:'Dream Team DTV' },
      championship: { nome:'Kings League Divino TV' },
      fase: 'final',
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },

    // ══════════════════════════════════════════════════════
    // Copa Divino Salão (championship_id: 4)
    // ══════════════════════════════════════════════════════
    {
      id: 24, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 6*24*3600000).toISOString(),
      local: 'Ginásio Divino TV', championship_id: 4,
      mandante_id: 15, visitante_id: 16,
      mandante: { id:15, nome:'Flash Futsal' }, visitante: { id:16, nome:'Trovão Futsal' },
      championship: { nome:'Copa Divino Salão' },
      resultado: { gols_mandante:5, gols_visitante:2 },
      gols: [
        { id:80, jogador:'Velozinho',  minuto: 5, tipo:'normal', team:{ nome:'Flash Futsal'  } },
        { id:81, jogador:'Velozinho',  minuto:18, tipo:'normal', team:{ nome:'Flash Futsal'  } },
        { id:82, jogador:'Trovação',   minuto:12, tipo:'normal', team:{ nome:'Trovão Futsal' } },
        { id:83, jogador:'Acrobata',   minuto:26, tipo:'normal', team:{ nome:'Flash Futsal'  } },
        { id:84, jogador:'Trovação',   minuto:37, tipo:'normal', team:{ nome:'Trovão Futsal' } },
        { id:85, jogador:'Velozinho',  minuto:44, tipo:'normal', team:{ nome:'Flash Futsal'  } },
        { id:86, jogador:'Pivô Flash', minuto:77, tipo:'normal', team:{ nome:'Flash Futsal'  } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:44, player:{ nome:'Velozinho' }, nota:9.0, melhor_jogo:true  },
        { id:45, player:{ nome:'Trovação'  }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Ana Paula', publico:230, observacoes:'Flash Futsal impecável. Velozinho hat-trick!' },
      link_video: null as string | null,
    },
    {
      id: 25, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 6*24*3600000).toISOString(),
      local: 'Ginásio Divino TV', championship_id: 4,
      mandante_id: 17, visitante_id: 18,
      mandante: { id:17, nome:'Star Futsal' }, visitante: { id:18, nome:'Relâmpago Futsal' },
      championship: { nome:'Copa Divino Salão' },
      resultado: { gols_mandante:4, gols_visitante:3 },
      gols: [
        { id:87, jogador:'Estrela',    minuto: 8, tipo:'normal', team:{ nome:'Star Futsal'      } },
        { id:88, jogador:'Raio',       minuto:14, tipo:'normal', team:{ nome:'Relâmpago Futsal' } },
        { id:89, jogador:'Estrela',    minuto:25, tipo:'normal', team:{ nome:'Star Futsal'      } },
        { id:90, jogador:'Faísca',     minuto:33, tipo:'normal', team:{ nome:'Relâmpago Futsal' } },
        { id:91, jogador:'Pivô Star',  minuto:39, tipo:'normal', team:{ nome:'Star Futsal'      } },
        { id:92, jogador:'Raio',       minuto:43, tipo:'normal', team:{ nome:'Relâmpago Futsal' } },
        { id:93, jogador:'Estrela',    minuto:47, tipo:'normal', team:{ nome:'Star Futsal'      } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:46, player:{ nome:'Estrela' }, nota:9.0, melhor_jogo:true  },
        { id:47, player:{ nome:'Raio'    }, nota:8.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Ana Paula', publico:230, observacoes:'Partida emocionante! Estrela hat-trick decide para o Star Futsal.' },
      link_video: null as string | null,
    },
    {
      id: 26, rodada: 2, status: 'agendado',
      data_hora: new Date(Date.now() + 7*24*3600000).toISOString(),
      local: 'Ginásio Divino TV', championship_id: 4,
      mandante_id: 15, visitante_id: 17,
      mandante: { id:15, nome:'Flash Futsal' }, visitante: { id:17, nome:'Star Futsal' },
      championship: { nome:'Copa Divino Salão' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
    {
      id: 27, rodada: 2, status: 'agendado',
      data_hora: new Date(Date.now() + 7*24*3600000).toISOString(),
      local: 'Ginásio Divino TV', championship_id: 4,
      mandante_id: 16, visitante_id: 18,
      mandante: { id:16, nome:'Trovão Futsal' }, visitante: { id:18, nome:'Relâmpago Futsal' },
      championship: { nome:'Copa Divino Salão' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
  ],

  classificacao: {
    1: [
      { team_id:2, team_nome:'Corinthians Base',  escudo_url:null, jogos:2, vitorias:2, empates:0, derrotas:0, gols_pro:7, gols_contra:0, saldo: 7, pontos:6 },
      { team_id:4, team_nome:'Palmeiras Jovem',   escudo_url:null, jogos:2, vitorias:2, empates:0, derrotas:0, gols_pro:4, gols_contra:0, saldo: 4, pontos:6 },
      { team_id:1, team_nome:'Flamengo Várzea',   escudo_url:null, jogos:2, vitorias:0, empates:0, derrotas:2, gols_pro:0, gols_contra:6, saldo:-6, pontos:0 },
      { team_id:3, team_nome:'Santos FC Amador',  escudo_url:null, jogos:2, vitorias:0, empates:0, derrotas:2, gols_pro:0, gols_contra:5, saldo:-5, pontos:0 },
    ],
    2: [
      { team_id:5, team_nome:'EC Mauá FC',       escudo_url:null, jogos:1, vitorias:1, empates:0, derrotas:0, gols_pro:2, gols_contra:1, saldo: 1, pontos:3 },
      { team_id:3, team_nome:'Santos FC Amador', escudo_url:null, jogos:1, vitorias:0, empates:1, derrotas:0, gols_pro:0, gols_contra:0, saldo: 0, pontos:1 },
      { team_id:4, team_nome:'Palmeiras Jovem',  escudo_url:null, jogos:1, vitorias:0, empates:1, derrotas:0, gols_pro:0, gols_contra:0, saldo: 0, pontos:1 },
      { team_id:6, team_nome:'União Diadema',    escudo_url:null, jogos:1, vitorias:0, empates:0, derrotas:1, gols_pro:1, gols_contra:2, saldo:-1, pontos:0 },
    ],
    3: [
      // ── Grupo A ──
      { team_id: 9, team_nome:'Divino All Stars', escudo_url:null, jogos:3, vitorias:3, empates:0, derrotas:0, gols_pro: 8, gols_contra: 3, saldo: 5, pontos:9, grupo:'A' },
      { team_id: 8, team_nome:'Team Craque',      escudo_url:null, jogos:3, vitorias:2, empates:0, derrotas:1, gols_pro: 7, gols_contra: 4, saldo: 3, pontos:6, grupo:'A' },
      { team_id: 7, team_nome:'Los Galácticos',   escudo_url:null, jogos:3, vitorias:1, empates:0, derrotas:2, gols_pro: 6, gols_contra: 6, saldo: 0, pontos:3, grupo:'A' },
      { team_id:10, team_nome:'Rei da Bola FC',   escudo_url:null, jogos:3, vitorias:0, empates:0, derrotas:3, gols_pro: 2, gols_contra:10, saldo:-8, pontos:0, grupo:'A' },
      // ── Grupo B ──
      { team_id:12, team_nome:'Dream Team DTV',   escudo_url:null, jogos:3, vitorias:2, empates:1, derrotas:0, gols_pro: 8, gols_contra: 3, saldo: 5, pontos:7, grupo:'B' },
      { team_id:11, team_nome:'Seleção ABC',       escudo_url:null, jogos:3, vitorias:2, empates:0, derrotas:1, gols_pro: 6, gols_contra: 3, saldo: 3, pontos:6, grupo:'B' },
      { team_id:13, team_nome:'Os Incríveis',      escudo_url:null, jogos:3, vitorias:1, empates:1, derrotas:1, gols_pro: 6, gols_contra: 5, saldo: 1, pontos:4, grupo:'B' },
      { team_id:14, team_nome:'Time do Povo',      escudo_url:null, jogos:3, vitorias:0, empates:0, derrotas:3, gols_pro: 1, gols_contra:10, saldo:-9, pontos:0, grupo:'B' },
    ],
    4: [
      { team_id:15, team_nome:'Flash Futsal',     escudo_url:null, jogos:1, vitorias:1, empates:0, derrotas:0, gols_pro:5, gols_contra:2, saldo: 3, pontos:3 },
      { team_id:17, team_nome:'Star Futsal',      escudo_url:null, jogos:1, vitorias:1, empates:0, derrotas:0, gols_pro:4, gols_contra:3, saldo: 1, pontos:3 },
      { team_id:18, team_nome:'Relâmpago Futsal', escudo_url:null, jogos:1, vitorias:0, empates:0, derrotas:1, gols_pro:3, gols_contra:4, saldo:-1, pontos:0 },
      { team_id:16, team_nome:'Trovão Futsal',    escudo_url:null, jogos:1, vitorias:0, empates:0, derrotas:1, gols_pro:2, gols_contra:5, saldo:-3, pontos:0 },
    ],
  } as Record<number, { team_id:number, team_nome:string, escudo_url:null, jogos:number, vitorias:number, empates:number, derrotas:number, gols_pro:number, gols_contra:number, saldo:number, pontos:number, grupo?:string }[]>,

  artilharia: [
    // ── Copa Divino TV ──
    { player_nome:'Diegão',        time:'Corinthians Base',  campeonato:'Copa Divino TV',    gols:5 },
    { player_nome:'Mateus',        time:'Palmeiras Jovem',   campeonato:'Copa Divino TV',    gols:2 },
    { player_nome:'Andrezinho',    time:'Corinthians Base',  campeonato:'Copa Divino TV',    gols:1 },
    { player_nome:'Júnior',        time:'Corinthians Base',  campeonato:'Copa Divino TV',    gols:1 },
    // ── Liga Sub-20 ──
    { player_nome:'Gabriel Costa', time:'EC Mauá FC',        campeonato:'Liga Sub-20',       gols:2 },
    { player_nome:'Felipe Neto',   time:'EC Mauá FC',        campeonato:'Liga Sub-20',       gols:1 },
    // ── Kings League ──
    { player_nome:'Craque Jr.',    time:'Team Craque',       campeonato:'Kings League DTV',  gols:5 },
    { player_nome:'Magrão',        time:'Dream Team DTV',    campeonato:'Kings League DTV',  gols:5 },
    { player_nome:'Divino King',   time:'Divino All Stars',  campeonato:'Kings League DTV',  gols:4 },
    { player_nome:'Fantasma',      time:'Os Incríveis',      campeonato:'Kings League DTV',  gols:4 },
    { player_nome:'Messinho',      time:'Divino All Stars',  campeonato:'Kings League DTV',  gols:3 },
    { player_nome:'El Galáctico',  time:'Los Galácticos',    campeonato:'Kings League DTV',  gols:3 },
    { player_nome:'Lindo',         time:'Seleção ABC',       campeonato:'Kings League DTV',  gols:3 },
    // ── Salão ──
    { player_nome:'Velozinho',     time:'Flash Futsal',      campeonato:'Copa Divino Salão', gols:3 },
    { player_nome:'Estrela',       time:'Star Futsal',       campeonato:'Copa Divino Salão', gols:3 },
    { player_nome:'Trovação',      time:'Trovão Futsal',     campeonato:'Copa Divino Salão', gols:2 },
    { player_nome:'Raio',          time:'Relâmpago Futsal',  campeonato:'Copa Divino Salão', gols:2 },
  ],

  premiacoes: [
    // ── Semana ──────────────────────────────────────────────────────────
    { id:1,  periodo:'semana', tipo:'melhor_jogo', referencia:'Rodada 2 · Copa DTV',       player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:2,  periodo:'semana', tipo:'artilheiro',  referencia:'Semana 14/abr',              player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:3,  periodo:'semana', tipo:'fair_play',   referencia:'Semana 14/abr',              player_nome:'Júnior',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:17, periodo:'semana', tipo:'melhor_jogo', referencia:'Kings League – Grupo A R3',  player_nome:'Divino King',  time_nome:'Divino All Stars', championship_nome:'Kings League Divino TV'},
    { id:18, periodo:'semana', tipo:'artilheiro',  referencia:'Kings League DTV',           player_nome:'Craque Jr.',   time_nome:'Team Craque',      championship_nome:'Kings League Divino TV'},
    // ── Mês ─────────────────────────────────────────────────────────────
    { id:4,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 1 · Copa DTV',        player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:5,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 2 · Copa DTV',        player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:6,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 1 · Sub-20',          player_nome:'Gabriel Costa',time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:7,  periodo:'mes',    tipo:'melhor_mes',  referencia:'Abril 2026',                 player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:8,  periodo:'mes',    tipo:'artilheiro',  referencia:'Abril 2026',                 player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:9,  periodo:'mes',    tipo:'fair_play',   referencia:'Abril 2026',                 player_nome:'Gabriel Costa',time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:19, periodo:'mes',    tipo:'melhor_jogo', referencia:'Kings League – Final do Dia',player_nome:'Divino King',  time_nome:'Divino All Stars', championship_nome:'Kings League Divino TV'},
    { id:20, periodo:'mes',    tipo:'artilheiro',  referencia:'Kings League DTV',           player_nome:'Craque Jr.',   time_nome:'Team Craque',      championship_nome:'Kings League Divino TV'},
    // ── Ano ─────────────────────────────────────────────────────────────
    { id:10, periodo:'ano',    tipo:'melhor_jogo', referencia:'Rodada 1 · Copa DTV',        player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:11, periodo:'ano',    tipo:'melhor_jogo', referencia:'Rodada 1 · Sub-20',          player_nome:'Gabriel Costa',time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:12, periodo:'ano',    tipo:'melhor_mes',  referencia:'Março 2026',                 player_nome:'Andrezinho',   time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:13, periodo:'ano',    tipo:'melhor_mes',  referencia:'Abril 2026',                 player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:14, periodo:'ano',    tipo:'melhor_ano',  referencia:'2025',                       player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:15, periodo:'ano',    tipo:'artilheiro',  referencia:'2026',                       player_nome:'Diegão',       time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:16, periodo:'ano',    tipo:'fair_play',   referencia:'2026',                       player_nome:'Gabriel Costa',time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:21, periodo:'ano',    tipo:'melhor_jogo', referencia:'Kings League DTV – Grupo B', player_nome:'Magrão',       time_nome:'Dream Team DTV',   championship_nome:'Kings League Divino TV'},
    { id:22, periodo:'ano',    tipo:'artilheiro',  referencia:'Kings League DTV 2026',      player_nome:'Craque Jr.',   time_nome:'Team Craque',      championship_nome:'Kings League Divino TV'},
  ],

  votacao_divino_league: {
    ativa: true,
    encerramento: '2026-05-31',
    descricao: 'Vote nos melhores jogadores da temporada para a Divino League 2026!',
    total_votos_referencia: 1482,
    posicoes: [
      {
        posicao: 'Goleiro', vagas: 1,
        candidatos: [
          { id:1,  nome:'Willian',     time:'Corinthians Base',  camp:'Copa Divino TV',    votos:342 },
          { id:2,  nome:'Rafa',        time:'Flamengo Várzea',   camp:'Copa Divino TV',    votos:198 },
          { id:3,  nome:'Deivison',    time:'EC Mauá FC',        camp:'Liga Sub-20 ABC',   votos:124 },
          { id:4,  nome:'Kauan',       time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos: 87 },
        ],
      },
      {
        posicao: 'Defensor', vagas: 4,
        candidatos: [
          { id:5,  nome:'Fábio',       time:'Corinthians Base',  camp:'Copa Divino TV',    votos:287 },
          { id:6,  nome:'Rodrigo',     time:'Corinthians Base',  camp:'Copa Divino TV',    votos:265 },
          { id:7,  nome:'Brunão',      time:'Flamengo Várzea',   camp:'Copa Divino TV',    votos:183 },
          { id:8,  nome:'Eduardo',     time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos:156 },
          { id:9,  nome:'Gilmar',      time:'Santos FC Amador',  camp:'Copa Divino TV',    votos: 98 },
          { id:10, nome:'Mauro',       time:'EC Mauá FC',        camp:'Liga Sub-20 ABC',   votos: 87 },
          { id:11, nome:'Vitor',       time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos: 73 },
          { id:12, nome:'Marcos Vini', time:'União Diadema',     camp:'Liga Sub-20 ABC',   votos: 54 },
        ],
      },
      {
        posicao: 'Meio-Campo', vagas: 4,
        candidatos: [
          { id:13, nome:'Andrezinho',  time:'Corinthians Base',  camp:'Copa Divino TV',    votos:401 },
          { id:14, nome:'Mateus',      time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos:312 },
          { id:15, nome:'Leandro',     time:'Corinthians Base',  camp:'Copa Divino TV',    votos:243 },
          { id:16, nome:'Paulo',       time:'Corinthians Base',  camp:'Copa Divino TV',    votos:198 },
          { id:17, nome:'Pedrinho',    time:'Flamengo Várzea',   camp:'Copa Divino TV',    votos:167 },
          { id:18, nome:'G. Costa',    time:'EC Mauá FC',        camp:'Liga Sub-20 ABC',   votos:145 },
          { id:19, nome:'Elias',       time:'União Diadema',     camp:'Liga Sub-20 ABC',   votos: 89 },
          { id:20, nome:'Cláudio',     time:'EC Mauá FC',        camp:'Liga Sub-20 ABC',   votos: 67 },
        ],
      },
      {
        posicao: 'Atacante', vagas: 4,
        candidatos: [
          { id:21, nome:'Diegão',      time:'Corinthians Base',  camp:'Copa Divino TV',    votos:523 },
          { id:22, nome:'Mateus',      time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos:289 },
          { id:23, nome:'Carlão',      time:'Flamengo Várzea',   camp:'Copa Divino TV',    votos:213 },
          { id:24, nome:'Júnior',      time:'Corinthians Base',  camp:'Copa Divino TV',    votos:187 },
          { id:25, nome:'Felipe Neto', time:'EC Mauá FC',        camp:'Liga Sub-20 ABC',   votos:134 },
          { id:26, nome:'Cleber',      time:'União Diadema',     camp:'Liga Sub-20 ABC',   votos: 98 },
          { id:27, nome:'Henrique',    time:'Santos FC Amador',  camp:'Copa Divino TV',    votos: 76 },
          { id:28, nome:'Juninho',     time:'Palmeiras Jovem',   camp:'Copa Divino TV',    votos: 54 },
        ],
      },
    ],
  },
}

export type EscalacaoJogador = {
  numero: number
  nome:   string
  posicao: string
  titular: boolean
}

export const ESCALACOES: Record<number, EscalacaoJogador[]> = {
  // ── Campo – Copa DTV / Sub-20 ─────────────────────────
  1: [ // Flamengo Várzea — 4-3-3
    { numero:1,  nome:'Rafa',       posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'Luca',       posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Marcos',     posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Brunão',     posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Fernando',   posicao:'Lateral E',     titular:true  },
    { numero:5,  nome:'André',      posicao:'Volante',       titular:true  },
    { numero:8,  nome:'Pedrinho',   posicao:'Meia',          titular:true  },
    { numero:10, nome:'Tiago',      posicao:'Meia',          titular:true  },
    { numero:7,  nome:'Rafael',     posicao:'Ponta D',       titular:true  },
    { numero:9,  nome:'Carlão',     posicao:'Centroavante',  titular:true  },
    { numero:11, nome:'Diogo',      posicao:'Ponta E',       titular:true  },
    { numero:12, nome:'Zé Paulo',   posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Wágner',     posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Denilson',   posicao:'Volante',       titular:false },
    { numero:17, nome:'Claudinho',  posicao:'Meia',          titular:false },
    { numero:18, nome:'Sávio',      posicao:'Atacante',      titular:false },
  ],
  2: [ // Corinthians Base — 4-4-2
    { numero:1,  nome:'Willian',    posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'Carlos',     posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Rodrigo',    posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Fábio',      posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Nilton',     posicao:'Lateral E',     titular:true  },
    { numero:7,  nome:'Andrezinho', posicao:'Meia D',        titular:true  },
    { numero:5,  nome:'Leandro',    posicao:'Volante',       titular:true  },
    { numero:8,  nome:'Paulo',      posicao:'Meia E',        titular:true  },
    { numero:11, nome:'Igor',       posicao:'Extremo',       titular:true  },
    { numero:9,  nome:'Diegão',     posicao:'Centroavante',  titular:true  },
    { numero:10, nome:'Júnior',     posicao:'Segunda Ponta', titular:true  },
    { numero:12, nome:'Marcelo',    posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Tião',       posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Marcão',     posicao:'Volante',       titular:false },
    { numero:17, nome:'Vinícius',   posicao:'Meia',          titular:false },
    { numero:18, nome:'Robson',     posicao:'Atacante',      titular:false },
  ],
  3: [ // Santos FC Amador — 4-2-3-1
    { numero:1,  nome:'Everton',    posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'Maikon',     posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Gilmar',     posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Thiagão',    posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Fábio',      posicao:'Lateral E',     titular:true  },
    { numero:5,  nome:'Marcos',     posicao:'Vol. Def.',     titular:true  },
    { numero:8,  nome:'Renan',      posicao:'Vol. Def.',     titular:true  },
    { numero:10, nome:'Gabi',       posicao:'Meia Atac.',    titular:true  },
    { numero:7,  nome:'Edson',      posicao:'Ponta D',       titular:true  },
    { numero:11, nome:'Léo',        posicao:'Ponta E',       titular:true  },
    { numero:9,  nome:'Henrique',   posicao:'Centroavante',  titular:true  },
    { numero:12, nome:'Adão',       posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Pires',      posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Zezão',      posicao:'Volante',       titular:false },
    { numero:17, nome:'Adriano',    posicao:'Meia',          titular:false },
    { numero:18, nome:'Serginho',   posicao:'Atacante',      titular:false },
  ],
  4: [ // Palmeiras Jovem — 4-3-3
    { numero:1,  nome:'Kauan',      posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'Gabriel',    posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Vitor',      posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Eduardo',    posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Breno',      posicao:'Lateral E',     titular:true  },
    { numero:5,  nome:'João',       posicao:'Volante',       titular:true  },
    { numero:8,  nome:'Mateus',     posicao:'Meia',          titular:true  },
    { numero:10, nome:'Lucas',      posicao:'Meia',          titular:true  },
    { numero:7,  nome:'Wendel',     posicao:'Ponta D',       titular:true  },
    { numero:9,  nome:'Juninho',    posicao:'Centroavante',  titular:true  },
    { numero:11, nome:'Pedro',      posicao:'Ponta E',       titular:true  },
    { numero:12, nome:'Douglas',    posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Rayan',      posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Wesley',     posicao:'Volante',       titular:false },
    { numero:17, nome:'Thales',     posicao:'Meia',          titular:false },
    { numero:18, nome:'Samuel',     posicao:'Atacante',      titular:false },
  ],
  5: [ // EC Mauá FC — 4-4-2
    { numero:1,  nome:'Deivison',   posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'Sandro',     posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Evaldo',     posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Mauro',      posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Michel',     posicao:'Lateral E',     titular:true  },
    { numero:7,  nome:'G. Costa',   posicao:'Meia D',        titular:true  },
    { numero:5,  nome:'Rafael',     posicao:'Volante',       titular:true  },
    { numero:8,  nome:'Cláudio',    posicao:'Meia E',        titular:true  },
    { numero:11, nome:'Tarcísio',   posicao:'Extremo',       titular:true  },
    { numero:9,  nome:'Felipe Neto',posicao:'Centroavante',  titular:true  },
    { numero:10, nome:'Robinho',    posicao:'Segunda Ponta', titular:true  },
    { numero:12, nome:'Toninho',    posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Nilton',     posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Murilo',     posicao:'Volante',       titular:false },
    { numero:17, nome:'Danilo',     posicao:'Meia',          titular:false },
    { numero:18, nome:'Alex',       posicao:'Atacante',      titular:false },
  ],
  6: [ // União Diadema — 4-3-3
    { numero:1,  nome:'Welton',     posicao:'Goleiro',       titular:true  },
    { numero:2,  nome:'André',      posicao:'Lateral D',     titular:true  },
    { numero:3,  nome:'Sérgio',     posicao:'Zagueiro',      titular:true  },
    { numero:4,  nome:'Marcos Vini',posicao:'Zagueiro',      titular:true  },
    { numero:6,  nome:'Paulo',      posicao:'Lateral E',     titular:true  },
    { numero:5,  nome:'Ricardo',    posicao:'Volante',       titular:true  },
    { numero:8,  nome:'Elias',      posicao:'Meia',          titular:true  },
    { numero:10, nome:'Henrique',   posicao:'Meia',          titular:true  },
    { numero:7,  nome:'Alisson',    posicao:'Ponta D',       titular:true  },
    { numero:9,  nome:'Cleber',     posicao:'Centroavante',  titular:true  },
    { numero:11, nome:'Fabrício',   posicao:'Ponta E',       titular:true  },
    { numero:12, nome:'João Paulo', posicao:'Goleiro',       titular:false },
    { numero:13, nome:'Iago',       posicao:'Zagueiro',      titular:false },
    { numero:15, nome:'Celso',      posicao:'Volante',       titular:false },
    { numero:17, nome:'Criciúma',   posicao:'Meia',          titular:false },
    { numero:18, nome:'Maikon',     posicao:'Atacante',      titular:false },
  ],

  // ── Kings League — 7v7 (7 titulares + 3 reservas) ────
  7: [ // Los Galácticos
    { numero:1,  nome:'Galáctico GK', posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Defensor 1',   posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Defensor 2',   posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Bola Presa',   posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Canhota',      posicao:'Meia',      titular:true  },
    { numero:9,  nome:'El Galáctico', posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Maestro',      posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Raé',          posicao:'Defensor',  titular:false },
    { numero:14, nome:'Luizão',       posicao:'Meia',      titular:false },
  ],
  8: [ // Team Craque
    { numero:1,  nome:'Pegão',        posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Blindado',     posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Parede',       posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Regateiro',    posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Veloz',        posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Craque Jr.',   posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Bolinha',      posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Perna',        posicao:'Defensor',  titular:false },
    { numero:14, nome:'Leveza',       posicao:'Meia',      titular:false },
  ],
  9: [ // Divino All Stars
    { numero:1,  nome:'Fortão',       posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Muralha',      posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Pedreira',     posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Bombeirinho',  posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Relâmpago',    posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Divino King',  posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Messinho',     posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Acelerado',    posicao:'Meia',      titular:false },
    { numero:14, nome:'Artístico',    posicao:'Atacante',  titular:false },
  ],
  10: [ // Rei da Bola FC
    { numero:1,  nome:'Muralha GK',   posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Ferreira',     posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Paulão',       posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Miúdo',        posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Toquinho',     posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Rei',          posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Príncipe',     posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Armador',      posicao:'Defensor',  titular:false },
    { numero:14, nome:'Xeque',        posicao:'Meia',      titular:false },
  ],
  11: [ // Seleção ABC
    { numero:1,  nome:'Guardião',     posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Bloqueio',     posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Firmeza',      posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Vento',        posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Lindo',        posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Rapidão',      posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Espinho',      posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Reserva',      posicao:'Defensor',  titular:false },
    { numero:14, nome:'Ponta ABC',    posicao:'Meia',      titular:false },
  ],
  12: [ // Dream Team DTV
    { numero:1,  nome:'Super GK',     posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Iron',         posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Steel',        posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Bombinha',     posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Veloz DTV',    posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Magrão',       posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Rápido',       posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Armour',       posicao:'Defensor',  titular:false },
    { numero:14, nome:'Flash DTV',    posicao:'Meia',      titular:false },
  ],
  13: [ // Os Incríveis
    { numero:1,  nome:'Capitão GK',   posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Rocha',        posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Pedra',        posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Esperto',      posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Trovão',       posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Fantasma',     posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Sombra',       posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Ágil',         posicao:'Defensor',  titular:false },
    { numero:14, nome:'Ninja',        posicao:'Meia',      titular:false },
  ],
  14: [ // Time do Povo
    { numero:1,  nome:'Guerreiro GK', posicao:'Goleiro',   titular:true  },
    { numero:2,  nome:'Força',        posicao:'Zagueiro',  titular:true  },
    { numero:3,  nome:'Garra',        posicao:'Zagueiro',  titular:true  },
    { numero:5,  nome:'Coração',      posicao:'Meia',      titular:true  },
    { numero:7,  nome:'Bravo',        posicao:'Meia',      titular:true  },
    { numero:9,  nome:'Tonelada',     posicao:'Atacante',  titular:true  },
    { numero:10, nome:'Guerreiro',    posicao:'Atacante',  titular:true  },
    { numero:12, nome:'Backup GK',    posicao:'Goleiro',   titular:false },
    { numero:13, nome:'Resistência',  posicao:'Defensor',  titular:false },
    { numero:14, nome:'Lutador',      posicao:'Meia',      titular:false },
  ],

  // ── Salão / Futsal (5 titulares + 3 reservas) ─────────
  15: [ // Flash Futsal
    { numero:1, nome:'Blindado',    posicao:'Goleiro',  titular:true  },
    { numero:2, nome:'Fixo Flash',  posicao:'Fixo',     titular:true  },
    { numero:3, nome:'Acrobata',    posicao:'Ala',      titular:true  },
    { numero:7, nome:'Velozinho',   posicao:'Ala',      titular:true  },
    { numero:9, nome:'Pivô Flash',  posicao:'Pivô',     titular:true  },
    { numero:12,nome:'Sub GK',      posicao:'Goleiro',  titular:false },
    { numero:4, nome:'Correria',    posicao:'Fixo',     titular:false },
    { numero:5, nome:'Rapidinho',   posicao:'Ala',      titular:false },
  ],
  16: [ // Trovão Futsal
    { numero:1, nome:'Muralha FS',  posicao:'Goleiro',  titular:true  },
    { numero:2, nome:'Fixo Trovão', posicao:'Fixo',     titular:true  },
    { numero:3, nome:'Ala Trovão',  posicao:'Ala',      titular:true  },
    { numero:7, nome:'Trovação',    posicao:'Ala',      titular:true  },
    { numero:9, nome:'Pivô Trovão', posicao:'Pivô',     titular:true  },
    { numero:12,nome:'Sub GK',      posicao:'Goleiro',  titular:false },
    { numero:4, nome:'Tempestade',  posicao:'Fixo',     titular:false },
    { numero:5, nome:'Relâmpago',   posicao:'Ala',      titular:false },
  ],
  17: [ // Star Futsal
    { numero:1, nome:'Super GK FS', posicao:'Goleiro',  titular:true  },
    { numero:2, nome:'Fixo Star',   posicao:'Fixo',     titular:true  },
    { numero:3, nome:'Meteoro',     posicao:'Ala',      titular:true  },
    { numero:7, nome:'Estrela',     posicao:'Ala',      titular:true  },
    { numero:9, nome:'Pivô Star',   posicao:'Pivô',     titular:true  },
    { numero:12,nome:'Sub GK',      posicao:'Goleiro',  titular:false },
    { numero:4, nome:'Nebulosa',    posicao:'Fixo',     titular:false },
    { numero:5, nome:'Cometa',      posicao:'Ala',      titular:false },
  ],
  18: [ // Relâmpago Futsal
    { numero:1, nome:'Barreira GK', posicao:'Goleiro',  titular:true  },
    { numero:2, nome:'Fixo Rel.',   posicao:'Fixo',     titular:true  },
    { numero:3, nome:'Faísca',      posicao:'Ala',      titular:true  },
    { numero:7, nome:'Raio',        posicao:'Ala',      titular:true  },
    { numero:9, nome:'Pivô Rel.',   posicao:'Pivô',     titular:true  },
    { numero:12,nome:'Sub GK',      posicao:'Goleiro',  titular:false },
    { numero:4, nome:'Choque',      posicao:'Fixo',     titular:false },
    { numero:5, nome:'Elétrico',    posicao:'Ala',      titular:false },
  ],
}

export function getMock<T>(key: keyof typeof MOCK_DATA): T {
  return MOCK_DATA[key] as T
}

export function mockJogadoresPorTime(teamId?: number) {
  if (!teamId) return []
  const time = MOCK_DATA.times.find(t => t.id === teamId)
  if (!time) return []
  return MOCK_DATA.jogadores
    .filter(j => j.time === time.nome)
    .map(j => ({ ...j, team_id: teamId }))
}
