// src/lib/mockData.ts
// Dados de demonstração para validação com Divino TV

export const MOCK_DATA = {

  campeonatos: [
    { id: 1, nome: 'Copa Divino TV 2026', categoria: 'Amador', temporada: 2026, status: 'ativo', org_id: '1' },
    { id: 2, nome: 'Liga Sub-20 ABC 2026', categoria: 'Sub-20', temporada: 2026, status: 'ativo', org_id: '1' },
  ],

  times: [
    { id: 1, nome: 'Flamengo Várzea',   cidade: 'Santo André' },
    { id: 2, nome: 'Corinthians Base',  cidade: 'São Paulo' },
    { id: 3, nome: 'Santos FC Amador',  cidade: 'Santos' },
    { id: 4, nome: 'Palmeiras Jovem',   cidade: 'São Paulo' },
    { id: 5, nome: 'EC Mauá FC',        cidade: 'Mauá' },
    { id: 6, nome: 'União Diadema',     cidade: 'Diadema' },
  ],

  jogadores: [
    { id: 1, nome: 'Carlos Eduardo Silva', apelido: 'Carlão',      posicao: 'atacante', time: 'Flamengo Várzea' },
    { id: 2, nome: 'João Pedro Ramos',     apelido: 'Pedrinho',    posicao: 'meia',     time: 'Flamengo Várzea' },
    { id: 3, nome: 'Rafael Costa Lima',    apelido: 'Rafa',        posicao: 'goleiro',  time: 'Flamengo Várzea' },
    { id: 4, nome: 'Bruno Oliveira',       apelido: 'Brunão',      posicao: 'zagueiro', time: 'Flamengo Várzea' },
    { id: 5, nome: 'Lucas Ferreira',       apelido: 'Luca',        posicao: 'lateral',  time: 'Flamengo Várzea' },
    { id: 6, nome: 'André Mendes',         apelido: 'Andrezinho',  posicao: 'volante',  time: 'Corinthians Base' },
    { id: 7, nome: 'Diego Souza',          apelido: 'Diegão',      posicao: 'atacante', time: 'Corinthians Base' },
    { id: 8, nome: 'Mateus Alves',         apelido: 'Mateus',      posicao: 'meia',     time: 'Palmeiras Jovem' },
  ],

  matches: [
    {
      id: 1, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 10*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera',
      championship_id: 1,
      mandante_id: 1, visitante_id: 2,
      mandante: { id: 1, nome: 'Flamengo Várzea' },
      visitante: { id: 2, nome: 'Corinthians Base' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: { gols_mandante: 3, gols_visitante: 1 },
      gols: [
        { id:1, jogador:'Carlão',    minuto:14, tipo:'normal',  team: { nome:'Flamengo Várzea' } },
        { id:2, jogador:'Pedrinho',  minuto:38, tipo:'normal',  team: { nome:'Flamengo Várzea' } },
        { id:3, jogador:'Diegão',    minuto:55, tipo:'normal',  team: { nome:'Corinthians Base' } },
        { id:4, jogador:'Carlão',    minuto:72, tipo:'penalti', team: { nome:'Flamengo Várzea' } },
      ],
      cartoes: [
        { id:1, jogador:'Andrezinho', minuto:34, tipo:'amarelo',        team: { nome:'Corinthians Base' } },
        { id:2, jogador:'Ricardinho', minuto:67, tipo:'amarelo',        team: { nome:'Corinthians Base' } },
      ],
      notas: [
        { id:1, player: { nome:'Carlão' },    nota:9.5, melhor_jogo:true  },
        { id:2, player: { nome:'Pedrinho' },  nota:7.5, melhor_jogo:false },
        { id:3, player: { nome:'Rafa' },      nota:7.0, melhor_jogo:false },
        { id:4, player: { nome:'Diegão' },    nota:6.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'José Santos', publico:320, observacoes:'Partida disputada. Público animado. Carlão decisivo.' },
      link_video: null as string | null,
    },
    {
      id: 2, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 10*24*3600000).toISOString(),
      local: 'Arena Várzea Norte',
      championship_id: 1,
      mandante_id: 3, visitante_id: 4,
      mandante: { id: 3, nome: 'Santos FC Amador' },
      visitante: { id: 4, nome: 'Palmeiras Jovem' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: { gols_mandante: 0, gols_visitante: 2 },
      gols: [
        { id:5, jogador:'Carlão',  minuto:29, tipo:'normal', team: { nome:'Palmeiras Jovem' } },
        { id:6, jogador:'Mateus',  minuto:61, tipo:'normal', team: { nome:'Palmeiras Jovem' } },
      ],
      cartoes: [
        { id:3, jogador:'Thiagão', minuto:50, tipo:'vermelho', team: { nome:'Santos FC Amador' } },
      ],
      notas: [
        { id:5, player: { nome:'Mateus' }, nota:8.0, melhor_jogo:true  },
        { id:6, player: { nome:'Carlão' }, nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Carlos Moreira', publico:210, observacoes:'Santos jogou com 10 desde os 50 minutos.' },
      link_video: null as string | null,
    },
    {
      id: 3, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 3*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera',
      championship_id: 1,
      mandante_id: 2, visitante_id: 3,
      mandante: { id: 2, nome: 'Corinthians Base' },
      visitante: { id: 3, nome: 'Santos FC Amador' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: { gols_mandante: 1, gols_visitante: 1 },
      gols: [
        { id:7, jogador:'Diegão', minuto:43, tipo:'normal', team: { nome:'Corinthians Base' } },
        { id:8, jogador:'Gabi',   minuto:78, tipo:'normal', team: { nome:'Santos FC Amador' } },
      ],
      cartoes: [
        { id:4, jogador:'Diegão', minuto:89, tipo:'amarelo_vermelho', team: { nome:'Corinthians Base' } },
      ],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
    {
      id: 4, rodada: 2, status: 'finalizado',
      data_hora: new Date(Date.now() - 3*24*3600000).toISOString(),
      local: 'Arena Várzea Norte',
      championship_id: 1,
      mandante_id: 4, visitante_id: 1,
      mandante: { id: 4, nome: 'Palmeiras Jovem' },
      visitante: { id: 1, nome: 'Flamengo Várzea' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: { gols_mandante: 2, gols_visitante: 0 },
      gols: [
        { id:9,  jogador:'Mateus', minuto:11, tipo:'normal',  team: { nome:'Palmeiras Jovem' } },
        { id:10, jogador:'Carlão', minuto:88, tipo:'contra',  team: { nome:'Flamengo Várzea' } },
      ],
      cartoes: [
        { id:5, jogador:'Brunão', minuto:23, tipo:'amarelo', team: { nome:'Flamengo Várzea' } },
      ],
      notas: [
        { id:7, player: { nome:'Mateus' }, nota:8.5, melhor_jogo:true  },
        { id:8, player: { nome:'Carlão' }, nota:6.0, melhor_jogo:false },
      ],
      sumula: { arbitro:'Carlos Moreira', publico:180, observacoes:'Jogo truncado na primeira etapa. Boa atuação do Palmeiras.' },
      link_video: null as string | null,
    },
    {
      id: 5, rodada: 3, status: 'agendado',
      data_hora: new Date(Date.now() + 4*24*3600000).toISOString(),
      local: 'Campo do Ibirapuera',
      championship_id: 1,
      mandante_id: 1, visitante_id: 3,
      mandante: { id: 1, nome: 'Flamengo Várzea' },
      visitante: { id: 3, nome: 'Santos FC Amador' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: 'https://youtube.com/watch?v=dQw4w9WgXcQ' as string | null,
    },
    {
      id: 6, rodada: 3, status: 'agendado',
      data_hora: new Date(Date.now() + 4*24*3600000).toISOString(),
      local: 'Arena Várzea Norte',
      championship_id: 1,
      mandante_id: 2, visitante_id: 4,
      mandante: { id: 2, nome: 'Corinthians Base' },
      visitante: { id: 4, nome: 'Palmeiras Jovem' },
      championship: { nome: 'Copa Divino TV 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
    {
      id: 7, rodada: 1, status: 'finalizado',
      data_hora: new Date(Date.now() - 7*24*3600000).toISOString(),
      local: 'Estádio Municipal Mauá',
      championship_id: 2,
      mandante_id: 5, visitante_id: 6,
      mandante: { id: 5, nome: 'EC Mauá FC' },
      visitante: { id: 6, nome: 'União Diadema' },
      championship: { nome: 'Liga Sub-20 ABC 2026' },
      resultado: { gols_mandante: 2, gols_visitante: 1 },
      gols: [
        { id:11, jogador:'Gabriel Costa', minuto:22, tipo:'normal', team: { nome:'EC Mauá FC' } },
        { id:12, jogador:'Felipe Neto',   minuto:55, tipo:'normal', team: { nome:'EC Mauá FC' } },
        { id:13, jogador:'Marcos Vini',   minuto:80, tipo:'normal', team: { nome:'União Diadema' } },
      ],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [
        { id:9,  player: { nome:'Gabriel Costa' }, nota:8.0, melhor_jogo:true  },
        { id:10, player: { nome:'Felipe Neto' },   nota:7.5, melhor_jogo:false },
      ],
      sumula: { arbitro:'Paulo Lima', publico:140, observacoes:'Boa partida entre as equipes jovens.' },
      link_video: null as string | null,
    },
    {
      id: 8, rodada: 2, status: 'agendado',
      data_hora: new Date(Date.now() + 6*24*3600000).toISOString(),
      local: 'Arena Sub-20 ABC',
      championship_id: 2,
      mandante_id: 4, visitante_id: 5,
      mandante: { id: 4, nome: 'Palmeiras Jovem' },
      visitante: { id: 5, nome: 'EC Mauá FC' },
      championship: { nome: 'Liga Sub-20 ABC 2026' },
      resultado: null as { gols_mandante:number, gols_visitante:number } | null,
      gols: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      cartoes: [] as { id:number, jogador:string, minuto:number, tipo:string, team:{nome:string} }[],
      notas: [] as { id:number, player:{nome:string}, nota:number, melhor_jogo:boolean }[],
      sumula: null as { arbitro:string, publico:number, observacoes:string } | null,
      link_video: null as string | null,
    },
  ],

  classificacao: {
    1: [
      { team_id:4, team_nome:'Palmeiras Jovem',   escudo_url:null, jogos:2, vitorias:2, empates:0, derrotas:0, gols_pro:4, gols_contra:0, saldo:4,  pontos:6 },
      { team_id:1, team_nome:'Flamengo Várzea',   escudo_url:null, jogos:2, vitorias:1, empates:0, derrotas:1, gols_pro:3, gols_contra:3, saldo:0,  pontos:3 },
      { team_id:2, team_nome:'Corinthians Base',  escudo_url:null, jogos:2, vitorias:0, empates:1, derrotas:1, gols_pro:2, gols_contra:4, saldo:-2, pontos:1 },
      { team_id:3, team_nome:'Santos FC Amador',  escudo_url:null, jogos:2, vitorias:0, empates:1, derrotas:1, gols_pro:1, gols_contra:3, saldo:-2, pontos:1 },
    ],
    2: [
      { team_id:5, team_nome:'EC Mauá FC',       escudo_url:null, jogos:1, vitorias:1, empates:0, derrotas:0, gols_pro:2, gols_contra:1, saldo:1,  pontos:3 },
      { team_id:3, team_nome:'Santos FC Amador', escudo_url:null, jogos:1, vitorias:0, empates:1, derrotas:0, gols_pro:0, gols_contra:0, saldo:0,  pontos:1 },
      { team_id:4, team_nome:'Palmeiras Jovem',  escudo_url:null, jogos:1, vitorias:0, empates:1, derrotas:0, gols_pro:0, gols_contra:0, saldo:0,  pontos:1 },
      { team_id:6, team_nome:'União Diadema',    escudo_url:null, jogos:1, vitorias:0, empates:0, derrotas:1, gols_pro:1, gols_contra:2, saldo:-1, pontos:0 },
    ]
  } as Record<number, { team_id:number, team_nome:string, escudo_url:null, jogos:number, vitorias:number, empates:number, derrotas:number, gols_pro:number, gols_contra:number, saldo:number, pontos:number }[]>,

  artilharia: [
    { player_nome:'Carlão',        time:'Flamengo Várzea',  gols:3 },
    { player_nome:'Mateus',        time:'Palmeiras Jovem',  gols:2 },
    { player_nome:'Gabriel Costa', time:'EC Mauá FC',       gols:2 },
    { player_nome:'Diegão',        time:'Corinthians Base', gols:1 },
  ],

  premiacoes: [
    // ── Semana ──────────────────────────────────────────────────────────
    { id:1,  periodo:'semana', tipo:'melhor_jogo', referencia:'Rodada 3 · Copa DTV',    player_nome:'Mateus',        time_nome:'Palmeiras Jovem',  championship_nome:'Copa Divino TV 2026'   },
    { id:2,  periodo:'semana', tipo:'artilheiro',  referencia:'Semana 15/abr',           player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    // ── Mês ─────────────────────────────────────────────────────────────
    { id:3,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 1 · Copa DTV',    player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:4,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 2 · Copa DTV',    player_nome:'Mateus',        time_nome:'Palmeiras Jovem',  championship_nome:'Copa Divino TV 2026'   },
    { id:5,  periodo:'mes',    tipo:'melhor_jogo', referencia:'Rodada 1 · Sub-20',      player_nome:'Gabriel Costa', time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:6,  periodo:'mes',    tipo:'melhor_mes',  referencia:'Abril 2026',              player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:7,  periodo:'mes',    tipo:'artilheiro',  referencia:'Abril 2026',              player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:8,  periodo:'mes',    tipo:'fair_play',   referencia:'Abril 2026',              player_nome:'Gabriel Costa', time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    // ── Ano ─────────────────────────────────────────────────────────────
    { id:9,  periodo:'ano',    tipo:'melhor_jogo', referencia:'Rodada 1 · Copa DTV',    player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:10, periodo:'ano',    tipo:'melhor_jogo', referencia:'Rodada 1 · Sub-20',      player_nome:'Gabriel Costa', time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
    { id:11, periodo:'ano',    tipo:'melhor_mes',  referencia:'Março 2026',              player_nome:'Diegão',        time_nome:'Corinthians Base', championship_nome:'Copa Divino TV 2026'   },
    { id:12, periodo:'ano',    tipo:'melhor_mes',  referencia:'Abril 2026',              player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:13, periodo:'ano',    tipo:'melhor_ano',  referencia:'2025',                    player_nome:'Mateus',        time_nome:'Palmeiras Jovem',  championship_nome:'Copa Divino TV 2026'   },
    { id:14, periodo:'ano',    tipo:'artilheiro',  referencia:'2026',                    player_nome:'Carlão',        time_nome:'Flamengo Várzea',  championship_nome:'Copa Divino TV 2026'   },
    { id:15, periodo:'ano',    tipo:'fair_play',   referencia:'2026',                    player_nome:'Gabriel Costa', time_nome:'EC Mauá FC',       championship_nome:'Liga Sub-20 ABC 2026' },
  ]
}

export type EscalacaoJogador = {
  numero: number
  nome: string
  posicao: string
  titular: boolean
}

export const ESCALACOES: Record<number, EscalacaoJogador[]> = {
  1: [ // Flamengo Várzea — 4-3-3
    { numero:1,  nome:'Rafa',       posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'Luca',       posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Marcos',     posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Brunão',     posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Fernando',   posicao:'Lateral E',  titular:true  },
    { numero:5,  nome:'André',      posicao:'Volante',    titular:true  },
    { numero:8,  nome:'Pedrinho',   posicao:'Meia',       titular:true  },
    { numero:10, nome:'Tiago',      posicao:'Meia',       titular:true  },
    { numero:7,  nome:'Rafael',     posicao:'Ponta D',    titular:true  },
    { numero:9,  nome:'Carlão',     posicao:'Centroavante',titular:true },
    { numero:11, nome:'Diogo',      posicao:'Ponta E',    titular:true  },
    { numero:12, nome:'Zé Paulo',   posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Wágner',     posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Denilson',   posicao:'Volante',    titular:false },
    { numero:17, nome:'Claudinho',  posicao:'Meia',       titular:false },
    { numero:18, nome:'Sávio',      posicao:'Atacante',   titular:false },
  ],
  2: [ // Corinthians Base — 4-4-2
    { numero:1,  nome:'Willian',    posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'Carlos',     posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Rodrigo',    posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Fábio',      posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Nilton',     posicao:'Lateral E',  titular:true  },
    { numero:7,  nome:'Andrezinho', posicao:'Meia D',     titular:true  },
    { numero:5,  nome:'Leandro',    posicao:'Volante',    titular:true  },
    { numero:8,  nome:'Paulo',      posicao:'Meia E',     titular:true  },
    { numero:11, nome:'Igor',       posicao:'Extremo',    titular:true  },
    { numero:9,  nome:'Diegão',     posicao:'Centroavante',titular:true },
    { numero:10, nome:'Júnior',     posicao:'Segunda Ponta',titular:true},
    { numero:12, nome:'Marcelo',    posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Tião',       posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Marcão',     posicao:'Volante',    titular:false },
    { numero:17, nome:'Vinícius',   posicao:'Meia',       titular:false },
    { numero:18, nome:'Robson',     posicao:'Atacante',   titular:false },
  ],
  3: [ // Santos FC Amador — 4-2-3-1
    { numero:1,  nome:'Everton',    posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'Maikon',     posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Gilmar',     posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Thiagão',    posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Fábio',      posicao:'Lateral E',  titular:true  },
    { numero:5,  nome:'Marcos',     posicao:'Vol. Def.',  titular:true  },
    { numero:8,  nome:'Renan',      posicao:'Vol. Def.',  titular:true  },
    { numero:10, nome:'Gabi',       posicao:'Meia Atac.', titular:true  },
    { numero:7,  nome:'Edson',      posicao:'Ponta D',    titular:true  },
    { numero:11, nome:'Léo',        posicao:'Ponta E',    titular:true  },
    { numero:9,  nome:'Henrique',   posicao:'Centroavante',titular:true },
    { numero:12, nome:'Adão',       posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Pires',      posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Zezão',      posicao:'Volante',    titular:false },
    { numero:17, nome:'Adriano',    posicao:'Meia',       titular:false },
    { numero:18, nome:'Serginho',   posicao:'Atacante',   titular:false },
  ],
  4: [ // Palmeiras Jovem — 4-3-3
    { numero:1,  nome:'Kauan',      posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'Gabriel',    posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Vitor',      posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Eduardo',    posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Breno',      posicao:'Lateral E',  titular:true  },
    { numero:5,  nome:'João',       posicao:'Volante',    titular:true  },
    { numero:8,  nome:'Mateus',     posicao:'Meia',       titular:true  },
    { numero:10, nome:'Lucas',      posicao:'Meia',       titular:true  },
    { numero:7,  nome:'Wendel',     posicao:'Ponta D',    titular:true  },
    { numero:9,  nome:'Juninho',    posicao:'Centroavante',titular:true },
    { numero:11, nome:'Pedro',      posicao:'Ponta E',    titular:true  },
    { numero:12, nome:'Douglas',    posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Rayan',      posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Wesley',     posicao:'Volante',    titular:false },
    { numero:17, nome:'Thales',     posicao:'Meia',       titular:false },
    { numero:18, nome:'Samuel',     posicao:'Atacante',   titular:false },
  ],
  5: [ // EC Mauá FC — 4-4-2
    { numero:1,  nome:'Deivison',   posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'Sandro',     posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Evaldo',     posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Mauro',      posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Michel',     posicao:'Lateral E',  titular:true  },
    { numero:7,  nome:'G. Costa',   posicao:'Meia D',     titular:true  },
    { numero:5,  nome:'Rafael',     posicao:'Volante',    titular:true  },
    { numero:8,  nome:'Cláudio',    posicao:'Meia E',     titular:true  },
    { numero:11, nome:'Tarcísio',   posicao:'Extremo',    titular:true  },
    { numero:9,  nome:'Felipe Neto',posicao:'Centroavante',titular:true },
    { numero:10, nome:'Robinho',    posicao:'Segunda Ponta',titular:true},
    { numero:12, nome:'Toninho',    posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Nilton',     posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Murilo',     posicao:'Volante',    titular:false },
    { numero:17, nome:'Danilo',     posicao:'Meia',       titular:false },
    { numero:18, nome:'Alex',       posicao:'Atacante',   titular:false },
  ],
  6: [ // União Diadema — 4-3-3
    { numero:1,  nome:'Welton',     posicao:'Goleiro',    titular:true  },
    { numero:2,  nome:'André',      posicao:'Lateral D',  titular:true  },
    { numero:3,  nome:'Sérgio',     posicao:'Zagueiro',   titular:true  },
    { numero:4,  nome:'Marcos Vini',posicao:'Zagueiro',   titular:true  },
    { numero:6,  nome:'Paulo',      posicao:'Lateral E',  titular:true  },
    { numero:5,  nome:'Ricardo',    posicao:'Volante',    titular:true  },
    { numero:8,  nome:'Elias',      posicao:'Meia',       titular:true  },
    { numero:10, nome:'Henrique',   posicao:'Meia',       titular:true  },
    { numero:7,  nome:'Alisson',    posicao:'Ponta D',    titular:true  },
    { numero:9,  nome:'Cleber',     posicao:'Centroavante',titular:true },
    { numero:11, nome:'Fabrício',   posicao:'Ponta E',    titular:true  },
    { numero:12, nome:'João Paulo', posicao:'Goleiro',    titular:false },
    { numero:13, nome:'Iago',       posicao:'Zagueiro',   titular:false },
    { numero:15, nome:'Celso',      posicao:'Volante',    titular:false },
    { numero:17, nome:'Criciúma',   posicao:'Meia',       titular:false },
    { numero:18, nome:'Maikon',     posicao:'Atacante',   titular:false },
  ],
}

export function getMock<T>(key: keyof typeof MOCK_DATA): T {
  return MOCK_DATA[key] as T
}
